title: Ibraheem Rodrigues
description: Programmer and Maker
url: https://ibraheemrodrigues.com
author: Ibraheem Rodrigues

logo: /assets/img/clip.png

lang: en_US

social:
  links:
    # - https://stackoverflow.com/users/8077162/ibraheem-rodrigues
    # - https://reddit.com/u/OBANx
    - https://github.com/IbraheemR
    - https://www.youtube.com/channel/UCKe4t2irPeZfM4w_Hf7X1NA
    # - https://www.codewars.com/users/IbraheemR

collections:
  projects:
    output: true
    permalink: /p/:year/:title/

defaults:
  - scope:
      path: ""
    values:
      draft: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: default

plugins:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
